apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay
spec:
  channel: stable
  installPlanApproval: Automatic
  name: quay
  source: community-operators
  sourceNamespace: openshift-marketplace
