apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig/quayecosystem.yaml

namespace: quay-enterprise

resources:
- quay-quayecosystem.yaml

secretGenerator:
- literals:
  - database-username=quay
  - database-password=password
  - database-root-password=password
  - database-name=quay
  name: database
- literals:
  - config-app-password=password
  name: quayconfig
- literals:
  - password=password
  name: redis
- literals:
  - superuser-email=quay@redhat.com
  - superuser-password=password
  - superuser-username=quay
  name: superuser
- files:
  - .dockerconfigjson=redhat-quay-pull-secret.json
  name: redhat-quay-pull-secret
  type: kubernetes.io/dockerconfigjson
