apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay
spec:
  quay:
    replicas: 3
    database:
      volumeSize: 1Gi
      resources:
        requests:
          cpu: 256m
          memory: 1Gi
    registryBackends:
      # configure your storage backend here
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
  clair:
    database:
      resources:
        requests:
          cpu: 256m
          memory: 1Gi
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
