apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay
spec:
  quay:
    database:
      volumeSize: 1Gi
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteMany
      persistentVolumeSize: 500Gi
