apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay
spec:
  quay:
    database:
      volumeSize: 1Gi
      resources:
        requests:
          cpu: 256m
          memory: 1Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ''
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteMany
      persistentVolumeSize: 500Gi
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
    nodeSelector:
      node-role.kubernetes.io/infra: ''
  redis:
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
    nodeSelector:
      node-role.kubernetes.io/infra: ''
  clair:
    database:
      resources:
        requests:
          cpu: 256m
          memory: 1Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ''
    resources:
      requests:
        cpu: 256m
        memory: 512Mi
    nodeSelector:
      node-role.kubernetes.io/infra: ''
